cemarapapua/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import  include
from django.conf.urls.static import  static
from cemarapapua import settings

urlpatterns = [
    # untuk path url aplikasi
    path('cemarapapuaAuth/', include('cemarapapuaAuth.urls')),
    path('dashboardadmin/', include('cemarapapua_app.urls')),
    path('', include('cemarapapua_frontend.urls')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cemarapapua_frontend/urls.py
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from cemarapapua_frontend.views import *

app_name = 'cemarapapua_front'
urlpatterns = [
    # routing ambil class dari view.py
    path('', Cemarapapua_front_index.as_view()),
    path('contact/', Contact.as_view(),name='contact'),
    path('kegiatan_gereja/', Kegiatan_gereja.as_view(),name='kegiatan_gereja'),
    path('firtu/', Firmantuhan.as_view(),name='firtu'),
    path('gallery_foto/', Foto.as_view(),name='gallery_foto'),
    path('gallery_video/', Video.as_view(),name='gallery_video'),
    path('opini/', Opini.as_view(),name='opini'),
    path('pemerintah/', Pemerintah.as_view(),name='pemerintah'),
    path('hukumpolitik/', Hukumpolitik.as_view(),name='hukumpolitik'),
    path('sosialbudaya/', SosialBudaya.as_view(),name='sosialbudaya'),
    path('pendidikan/', Pendidikan.as_view(),name='pendidikan'),
    path('ekonomi/', Ekonomi.as_view(),name='ekonomi'),
    path('kesehatan/', Kesehatan.as_view(),name='kesehatan'),
    path('Detail_post/<int:pk>/', Detail_post.as_view(), name='detailposts'),
    path('Detail_firtu/<int:pk>/', Detail_firtu.as_view(), name='detailfirtu'),
    
  

]

templates/frontend/detail_firtu.html
{% extends "frontend/index.html" %}
{% load static %}
{% load custom_tags %}
{% block content %}

<section class="blog_area single-post-area section-padding">
    <div class="container">
       <div class="row">
           
          <div class="col-lg-8 posts-list">
             <div class="single-post">
                {% for detailfirtu in ViewDetailFirtu %}
                <div class="feature-img">
                   <img class="img-fluid" src="{{ detailfirtu.firtu_img|generate_thumbnail }}" alt="">
                   <!-- <label style="font-size: small;"><i></i></label> -->
                </div>
                <div class="blog_details">
                   <h2>{{ detailfirtu.firtu_title }}</h2>
                    <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="#"><i class="fa fa-calendar"></i> {{ detailfirtu.firtu_date }}</a></li>
                    </ul>
                    <!-- {% autoescape off %} -->
                        {{ detailfirtu.firtu_desc }}
                    <!-- {% endautoescape %} -->
                   
                </div>
                {% endfor %}
             </div>
             <div class="navigation-top">
                <div class="d-sm-flex justify-content-between text-center">
                   <div class="col-sm-4 text-center my-2 my-sm-0">
                      <p class="comment-count"><span class="align-middle"><span class="fa fa-edit"></span> Penulis : Admin</p>
                   </div>
                   <ul class="social-icons">
                      <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                   </ul>
                </div>
             </div>
             <div class="comments-area">
                <h4>05 Comments</h4>
                {% for ListCommentar in ViewCOmmentar %}
                <div class="comment-list">
                   <div class="single-comment justify-content-between d-flex">
                      <div class="user justify-content-between d-flex">
                         <div class="thumb">
                            <!-- <img src="assets/img/comment/comment_3.png" alt=""> -->
                            <span class="fa fa-comments"></span>
                         </div>
                        
                         <div class="desc">
                            <p class="comment">
                               {{ ListCommentar.pesan }}
                            </p>
                            <div class="d-flex justify-content-between">
                               <div class="d-flex align-items-center">
                                  <h5>
                                     <a href="#"><span class="fa fa-user"></span> {{ ListCommentar.full_name }}</a>
                                  </h5>
                                  <p class="date">{{ ListCommentar.com_date }}</p>
                               </div>
                               <div class="reply-btn">
                                  <a href="#" class="btn-reply text-uppercase"><span class="fa fa-reply"></span> Balas</a>
                               </div>
                            </div>
                         </div>
                      
                      </div>
                   </div>
                </div>
                {% endfor %}
             </div>
             <div class="weekly2-news-area pt-50 pb-30 gray-bg">
              <div class="container">
                  <div class="weekly2-wrapper">
                     
                      <div class="row">
      
                          <div class="col-lg-12">
                              <div class="slider-wrapper">
                                  <!-- section Tittle -->
                                  <div class="row">
                                      <div class="col-lg-12">
                                          <div class="small-tittle mb-30">
                                              <h4>Berita Utama</h4>
                                          </div>
                                      </div>
                                  </div>
                                  <!-- Slider -->
                                  <div class="row">
                                      <div class="col-lg-12">
                                          <div class="weekly2-news-active d-flex">
                                              <!-- Single -->
                                              {% for listBeritaTerkait in beritaTerkait %}
                                              <div class="weekly2-single">
                                                <div class="weekly2-img">
                                                    <img src="{{ listBeritaTerkait.posts_img|generate_thumbnail }}" alt="" width="202" height="133">
                                                    <p align='justify' style="font-size: 12px;">{{listBeritaTerkait.user_id.full_name}}  | {{listBeritaTerkait.posts_date}} </p>
                                                </div>
                                                <div class="weekly2-caption">
                                                    <span style="background-color: #14f8e9; padding: 3px; border-radius: 2px; font-size: small;"><b>{{listBeritaTerkait.category_id.categorys}}</b></span>
                                                    <h4><a href="{% url 'cemarapapua_front:detailposts' listBeritaTerkait.posts_id %}">{{listBeritaTerkait.posts_title}}</a></h4>
                                                    
                                                </div>
                                              </div>
                                              {% endfor %}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>  
             <div class="comment-form">
                <h4>Leave a Reply</h4>
                <form class="form-contact comment_form" action="#" id="commentForm">
                   <div class="row">
                      <div class="col-12">
                         <div class="form-group">
                            <textarea class="form-control w-100" name="comment" id="comment" cols="30" rows="9"
                               placeholder="Write Comment"></textarea>
                         </div>
                      </div>
                      <div class="col-sm-6">
                         <div class="form-group">
                            <input class="form-control" name="name" id="name" type="text" placeholder="Name">
                         </div>
                      </div>
                      <div class="col-sm-6">
                         <div class="form-group">
                            <input class="form-control" name="email" id="email" type="email" placeholder="Email">
                         </div>
                      </div>
                      <div class="col-12">
                         <div class="form-group">
                            <input class="form-control" name="website" id="website" type="text" placeholder="Website">
                         </div>
                      </div>
                   </div>
                   <div class="form-group">
                      <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
                   </div>
                </form>
             </div>
             
          </div>
          <div class="col-lg-4">
              <div class="blog_right_sidebar">
                  <aside class="single_sidebar_widget search_widget">
                      <form action="#">
                          <div class="form-group">
                              <div class="input-group mb-3">
                                  <input type="text" class="form-control" placeholder='Search Keyword'
                                      onfocus="this.placeholder = ''"
                                      onblur="this.placeholder = 'Search Keyword'">
                                  <div class="input-group-append">
                                      <button class="btns" type="button"><i class="ti-search"></i></button>
                                  </div>
                              </div>
                          </div>
                          <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                              type="submit">Search</button>
                      </form>
                  </aside>
                  <aside class="single_sidebar_widget post_category_widget">
                    <h4 class="widget_title">Kategori</h4>
                    <ul class="list cat-list">
  
                      {% for categoryNews in dataJumlahKategori %}
                          <li>
                              <a href="#" class="d-flex">
                                  <p>{{ categoryNews.categorys }}</p>
                                  <p>&nbsp;({{categoryNews.count_post}})</p>
                              </a>
                          </li>
                      {% endfor %}
  
                    </ul>
                </aside>
                <aside class="single_sidebar_widget popular_post_widget">
                    <h3 class="widget_title">Terpopuler</h3>
                          {% for dataTerpopuler in databeritaTerpopulerView %}
                              <div class="media post_item">
                                  <img src="{{ dataTerpopuler.posts_img|generate_thumbnail }}" alt="post" width="80px" height="80px">
                                  <div class="media-body">
                                      <a href="{% url 'cemarapapua_front:detailposts' dataTerpopuler.posts_id %}">
                                          <h3>{{ dataTerpopuler.posts_title }}</h3>
                                      </a>
                                      <p>{{ dataTerpopuler.posts_date }}</p>
                                  </div>
                              </div>
                          {% endfor %}
                </aside>
                <aside class="single_sidebar_widget popular_post_widget">
                    <h3 class="widget_title">Firman Tuhan</h3>
                    {% for dataListFirtu in dataFirtuView %}
                    <div class="media post_item">
                        <!-- <img src="{% static 'frontend/img/news_/' %}{{ dataTerpopuler.posts_img }}" alt="post" width="80px" height="80px"> -->
                        <div class="media-body">
                            <a href="{% url 'cemarapapua_front:detailfirtu' dataListFirtu.firtu_id %}">
                                <h3>{{ dataListFirtu.firtu_title }}</h3>
                            </a>
                             <!-- {% autoescape off %} -->
                            {{ dataListFirtu.firtu_desc|slice:":255"}}
                            <!-- {% endautoescape %} -->
                        </div>
                    </div>
                    {% endfor %}
                </aside>
                <aside class="single_sidebar_widget popular_post_widget">
                      <h3 class="widget_title">Kegiatan Gereja</h3>
                      {% for terkaitGereja in dataViewGereja %}
                      <div class="media post_item">
                          <img src="{{ terkaitGereja.posts_img|generate_thumbnail }}" width="80px" height="80px">
                          <div class="media-body">
                              <a href="{% url 'cemarapapua_front:detailposts' terkaitGereja.posts_id %}">
                                  <h3>{{ terkaitGereja.posts_title }}</h3>
                              </a>
                              <p>{{ terkaitGereja.posts_date }}</p>
                          </div>
                      </div>
                      {% endfor %}
                      
                </aside>   
              </div>
          </div>
       </div>
    </div>
 </section>


{% endblock %}

templates/frontend/ekonomi.html
{% extends "frontend/index.html" %}
{% load static %}
{% load custom_tags %}
{% block content %}
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding" style="padding-top: 10px;">
    <div class="container">
       <div class="row">
          <div class="col-lg-8 posts-list">
            <div class="blog_left_sidebar">
                    {% for listEkonomi in dataVberitaekonomi  %}

                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{ listEkonomi.posts_img|generate_thumbnail }}" alt="" width="" height="380">
                            <a href="#" class="blog_item_date">
                                <h3>15</h3>
                                <p>Jan</p>
                            </a>
                        </div>

                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'cemarapapua_front:detailposts' listEkonomi.posts_id %}">
                                <h2>{{ listEkonomi.posts_title }}</h2>
                            </a>
                             <!-- {% autoescape off %} -->
                                {{ listEkonomi.posts_desc|slice:":255"}}
                             <!-- {% endautoescape %} -->
                             <a href="{% url 'cemarapapua_front:detailposts' listEkonomi.posts_id %}" style="background-color:rgb(9, 236, 122) ; padding: 5px; border-radius: 5px;"><i><b>Baca Selanjutnya</b> </i></a>

                             <p>
                                Keyword:<span style="background-color:#f1efd7; border-radius: 2px;"><i> {{ listEkonomi.posts_keyword }}</i></span>
                             </p>
                            <ul class="blog-info-link">
                                <li><a href="#"><i class="fa fa-user"></i> {{ listEkonomi.user_id.full_name }}</a></li>
                                <li><a href="#"><i class="fa fa-comments"></i> 03 Comments</a></li>
                                <li><a href="#"><i class="fa fa-label"></i> {{ listEkonomi.category_id.categorys }}</a></li>
                                <li><a href="#"><i class="fa fa-calendar"></i> {{ listEkonomi.posts_date }}</a></li>
                            </ul>

                        </div>
                    </article>

                    {% endfor %}

                   

                    <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link">1</a>
                            </li>
                            <li class="page-item active">
                                <a href="#" class="page-link">2</a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    
                </div>
           
           
             <div class="weekly2-news-area pt-50 pb-30 gray-bg">
              <div class="container">
                  <div class="weekly2-wrapper">
                     
                      <div class="row">
      
                          <div class="col-lg-12">
                              <div class="slider-wrapper">
                                  <!-- section Tittle -->
                                  <div class="row">
                                      <div class="col-lg-12">
                                          <div class="small-tittle mb-30">
                                              <h4>Berita Terkait</h4>
                                          </div>
                                      </div>
                                  </div>
                                  <!-- Slider -->
                                  <div class="row">
                                      <div class="col-lg-12">
                                          <div class="weekly2-news-active d-flex">
                                              <!-- Single -->
                                              {% for listBeritaTerkait in beritaTerkait %}
                                                <div class="weekly2-single">
                                                    <div class="weekly2-img">
                                                        <img src="{{ listBeritaTerkait.posts_img|generate_thumbnail }}" alt="" width="202" height="133">
                                                        <p align='justify' style="font-size: 12px;">{{listBeritaTerkait.user_id.full_name}}  | {{listBeritaTerkait.posts_date}} </p>
                                                    </div>
                                                    <div class="weekly2-caption">
                                                        <span style="background-color: #14f8e9; padding: 3px; border-radius: 2px; font-size: small;"><b>{{listBeritaTerkait.category_id.categorys}}</b></span>
                                                        <h4><a href="{% url 'cemarapapua_front:detailposts' listBeritaTerkait.posts_id %}">{{listBeritaTerkait.posts_title}}</a></h4>
                                                        
                                                    </div>
                                                </div> 
                                              {% endfor %}
                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>  
             
             
          </div>
          <div class="col-lg-4">
              <div class="blog_right_sidebar">
                  <aside class="single_sidebar_widget search_widget">
                      <form action="#">
                          <div class="form-group">
                              <div class="input-group mb-3">
                                  <input type="text" class="form-control" placeholder='Search Keyword'
                                      onfocus="this.placeholder = ''"
                                      onblur="this.placeholder = 'Search Keyword'">
                                  <div class="input-group-append">
                                      <button class="btns" type="button"><i class="ti-search"></i></button>
                                  </div>
                              </div>
                          </div>
                          <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                              type="submit">Search</button>
                      </form>
                  </aside>
                  <aside class="single_sidebar_widget post_category_widget">
                    <h4 class="widget_title">Kategori</h4>
                    <ul class="list cat-list">

                      {% for categoryNews in dataJumlahKategori %}
                          <li>
                              <a href="#" class="d-flex">
                                  <p>{{ categoryNews.categorys }}</p>
                                  <p>&nbsp;({{categoryNews.count_post}})</p>
                              </a>
                          </li>
                      {% endfor %}

                    </ul>
                </aside>
                  <aside class="single_sidebar_widget popular_post_widget">
                      <h3 class="widget_title">Terpopuler</h3>
                            {% for dataTerpopuler in databeritaTerpopulerView %}
                                <div class="media post_item">
                                    <img src="{{ dataTerpopuler.posts_img|generate_thumbnail }}" alt="post" width="80px" height="80px">
                                    <div class="media-body">
                                        <a href="{% url 'cemarapapua_front:detailposts' dataTerpopuler.posts_id %}">
                                            <h3>{{ dataTerpopuler.posts_title }}</h3>
                                        </a>
                                        <p>{{ dataTerpopuler.posts_date }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                      
                  </aside>

                  <aside class="single_sidebar_widget popular_post_widget">
                    <h3 class="widget_title">Firman Tuhan</h3>
                    {% for dataListFirtu in dataFirtuView %}
                    <div class="media post_item">
                        <!-- <img src="{% static 'frontend/img/news_/' %}{{ dataTerpopuler.posts_img }}" alt="post" width="80px" height="80px"> -->
                        <div class="media-body">
                            <a href="{% url 'cemarapapua_front:detailfirtu' dataListFirtu.firtu_id %}">
                                <h3>{{ dataListFirtu.firtu_title }}</h3>
                            </a>
                            <!-- <p>"{{ dataListFirtu.firtu_desc }}"</p> -->
                        </div>
                    </div>
                    {% endfor %}
                </aside>
                  
              </div>
          </div>
       </div>
    </div>
 </section>
 <!--================ Blog Area end =================-->
 {% endblock %}

templates/frontend/firtu.html
{% extends "frontend/index.html" %}
{% load static %}
{% block content %}
<div class="about-area2 gray-bg pt-60 pb-60">
    <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Trending Tittle -->
                    <div class="about-right mb-90">
                        <!-- <div class="about-img">
                            <img src="{% static 'frontend/img/trending/trending_top.jpg' %}" alt="">
                        </div> -->
                        <div class="heading-news mb-30 pt-30">
                            <h3>Daftar Firman Tuhan</h3>
                        </div>
                        {% for firtuView in dataFirtuView %}
                        <div class="about-prea" >
                            <div class="section-top-border" style="padding: 10px;">
                                <a href=""><h3 class="mb-30" style="margin-bottom: 15px; font-size: medium;"><span class="fa fa-book"></span> {{firtuView.firtu_title}}</h3></a>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <blockquote class="generic-blockquote" style="padding: 15px;">
                                             <!-- {% autoescape off %} -->
                                                "{{firtuView.firtu_desc|slice:":255"}}"
                                                <!-- {% endautoescape %} -->

                                                <br><a href="{% url 'cemarapapua_front:detailfirtu' firtuView.firtu_id %}" style="color: darkkhaki;"><span class="fa fa-eye"></span> Baca Selanjutnya</a>
                                        </blockquote>
                                        <div class="social-share pt-30" style="padding: 0px;">
                                            <div class="section-tittle">
                                                <h3 class="mr-20" style="font-size: medium;">Share:</h3>
                                                <ul>
                                                    <li><a href="#"><img src="{% static 'frontend/img/news/icon-ins.png' %}" alt=""></a></li>
                                                    <li><a href="#"><img src="{% static 'frontend/img/news/icon-fb.png' %}" alt=""></a></li>
                                                    <li><a href="#"><img src="{% static 'frontend/img/news/icon-tw.png' %}" alt=""></a></li>
                                                    
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> 
                      {% endfor %}
                      
                      <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link">1</a>
                            </li>
                            <li class="page-item active">
                                <a href="#" class="page-link">2</a>
                            </li>
                            <li class="page-item">
                                <a href="#" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Kategori</h4>
                            <ul class="list cat-list">
                                {% for categoryNews in dataJumlahKategori %}
                                <li>
                                    <a href="#" class="d-flex">
                                        <p>{{ categoryNews.categorys }}</p>
                                        <p>&nbsp;({{categoryNews.count_post}})</p>
                                    </a>
                                </li>
                          {% endfor %}
                            </ul>
                        </aside>
                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">Terpopuler</h3>
                            {% for dataTerpopuler in databeritaTerpopulerView %}
                            <div class="media post_item">
                                <img src="{% static 'frontend/img/news_/' %}{{ dataTerpopuler.posts_img }}" alt="post" width="80px" height="80px">
                                <div class="media-body">
                                    <a href="{% url 'cemarapapua_front:detailposts' dataTerpopuler.posts_id %}">
                                        <h3>{{ dataTerpopuler.posts_title }}</h3>
                                    </a>
                                    <p>{{ dataTerpopuler.posts_date }}</p>
                                </div>
                            </div>
                            {% endfor %}
                        </aside>
    
                        
                    </div>
                   
                </div>
                <div class="row">
                    <div class="col-md-12">
                        {% include 'frontend/kegiatan_terkait.html' %}
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}